# Generated by Django 5.0.3 on 2026-03-29 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('condition_type', models.CharField(choices=[('amount', 'Amount-based'), ('category', 'Category-based'), ('role', 'Role-based'), ('combined', 'Combined Conditions')], max_length=20)),
                ('condition_config', models.JSONField()),
                ('action_type', models.CharField(choices=[('add_step', 'Add Approval Step'), ('override', 'Override Approval'), ('auto_approve', 'Auto Approve')], max_length=20)),
                ('action_config', models.JSONField()),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='companies.company')),
            ],
            options={
                'db_table': 'rules',
                'ordering': ['-priority', 'id'],
                'indexes': [models.Index(fields=['company', 'is_active', '-priority'], name='rules_company_ea136f_idx')],
            },
        ),
    ]
