# Generated by Django 5.0.3 on 2026-03-29 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.expense'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'status'], name='expenses_user_id_389a02_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'status'], name='expenses_company_4436bb_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['submission_date'], name='expenses_submiss_a831c6_idx'),
        ),
    ]
