# Generated by Django 5.0.3 on 2026-03-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Expense Created'), ('submitted', 'Expense Submitted'), ('approval_requested', 'Approval Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated'), ('completed', 'Completed')], max_length=30)),
                ('comments', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'approval_logs',
                'ordering': ['timestamp'],
            },
        ),
    ]
