# Generated by Django 5.0.3 on 2026-03-29 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approver',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('flow', 'sequence_order')},
        ),
        migrations.AddIndex(
            model_name='approver',
            index=models.Index(fields=['user', 'status'], name='approvers_user_id_1337ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approver',
            unique_together={('step', 'user')},
        ),
    ]
