# Generated by Django 5.0.3 on 2026-03-29 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_url', models.CharField(max_length=500)),
                ('extracted_data', models.JSONField()),
                ('confidence_score', models.FloatField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_data', to='expenses.expense')),
            ],
            options={
                'db_table': 'ocr_extractions',
            },
        ),
    ]
